second commit
rust2014/go-first-floor-sprint-five pull request #1
Opened 2024-02-18 13:28 UTC by rust2014

2024-02-18 14:14 UTC, just-musha requested changes
Привет! Хорошая работа! Давай поправим формулу калорий для Swimming (комментарий оставила в коде), и ещё добавим проверки на 0, где это необходимо. В остальном - супер, все по заданию и формулы корректны. Присылай правки.

2024-02-18 14:14 UTC, just-musha commented on main.go
> +	return t.distance() / t.Duration.Hours()
А что если Duration равен 0 ? Давай добавим проверку на 0, как было в 4 спринте. Здесь и ниже по коду, где есть деление

2024-02-18 14:14 UTC, just-musha commented on main.go
> +	return ((CaloriesWeightMultiplier*w.Weight + (math.Pow(w.meanSpeed()*KmHInMsec, 2)/w.Height)*CaloriesSpeedHeightMultiplier*w.Weight) * w.Duration.Hours() * MinInHours)
Внешние скобки можно убрать, они ни на что не влияют

2024-02-18 14:14 UTC, just-musha commented on main.go
> +	return s.Training.TrainingInfo()
Вот здесь важный момент: в running/walking у нас скорость рассчитывается по "базовой" формуле, которая есть в Training. В случае с плаванием, скорость вычисляется в конкретной реализации meanSpeed для Swimming. Здесь тебе нужно явно вызвать метод s.meanSpeed() для Swimming и положить значения в нужное поле

2024-02-19 20:55 UTC, rust2014 commented
Спасибо!
Отправил правки

2024-02-20 03:28 UTC, just-musha approved these changes
Спасибо! Отписала в комментариях, где проверки не обязательны. Это не критично для принятия работы, но обрати внимание на будущее.

2024-02-20 03:28 UTC, just-musha commented on main.go
> +	if duration == 0 {
Вот здесь это не нужно, тк нет деления на duration, с ним проблем не будет

А вот для `Height` - можно бы добавить

2024-02-20 03:28 UTC, just-musha commented on main.go
> +	duration := s.Duration.Hours()
И здесь только умножение, проверка не нужна

2024-02-20 03:28 UTC, just-musha commented on main.go
> +	return (CaloriesMeanSpeedMultiplier*r.meanSpeed() + CaloriesMeanSpeedShift) * r.Weight / MInKm * duration * MinInHours
И тут не нужна

2024-02-20 14:12 UTC, closed without merging